GET  http://localhost:3333/ 
content-type: application/json

{
    "origin": "rua minas gerais cabreuva",
    "destination": "rIO DE JANEIRO",
    "KmPerLiter": 6,
    "bussTicket": 6,
    "trainTicket": 7,
    "haveBike": "yes"
}